const Formula = ({ children }: { children: React.ReactNode }) => <p className="overflow-x-auto rounded-md bg-slate-100 px-4 py-3 font-semibold text-slate-900">{children}</p>;
const Table = ({ headers, rows }: { headers: string[]; rows: React.ReactNode[][] }) => <div className="overflow-x-auto rounded-md border border-slate-200"><table className="w-full min-w-[34rem] border-collapse text-left text-sm"><thead className="bg-slate-100"><tr>{headers.map(header => <th key={header} scope="col" className="border-b border-slate-300 px-4 py-3 font-bold">{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-b border-slate-200 last:border-0">{row.map((cell, cellIndex) => cellIndex === 0 ? <th key={cellIndex} scope="row" className="px-4 py-3 font-semibold">{cell}</th> : <td key={cellIndex} className="px-4 py-3">{cell}</td>)}</tr>)}</tbody></table></div>;

export function RetirementArticle() {
  return <article className="retirement-article mx-auto max-w-4xl space-y-8 text-[15px] leading-7 text-slate-700">
    <header className="space-y-4"><h2 className="text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">UK Retirement Calculator: Estimate Your Future Savings</h2>
      <p>Planning for retirement starts with understanding how your savings could grow and what might affect their future value. The NexoraCalculator Retirement Calculator estimates the savings you could build by your chosen retirement age, based on your current savings, monthly contributions and expected annual return.</p>
      <p>Compare different scenarios to explore how saving more, retiring later or changing your investment return assumption affects the projection. Use the results alongside your pension statements and retirement budget to prepare for the future.</p></header>

    <section><h3>What the retirement calculator shows</h3><p>This calculator provides a simplified retirement savings projection with three main results:</p><ul><li><strong>Projected retirement savings:</strong> The estimated balance at your selected retirement age.</li><li><strong>Total contributions:</strong> Your starting savings plus the monthly contributions added during the projection.</li><li><strong>Total growth:</strong> The difference between the projected balance and total contributions.</li></ul><p>The starting balance is included under total contributions for this calculation, even if some of those existing savings came from earlier investment growth.</p><p>The calculator projects the accumulation of savings <strong>before retirement</strong>. It does not calculate a retirement income, recommend a withdrawal rate or estimate how long your money will last after you stop contributing.</p></section>

    <section><h3>How to use the retirement calculator</h3><ol><li><strong>Select the display currency.</strong> Keep all savings and contribution amounts in the same currency.</li><li><strong>Enter your current age.</strong> This establishes the starting point for the projection.</li><li><strong>Choose your planned retirement age.</strong> The difference between the two ages determines the saving period.</li><li><strong>Enter your current savings.</strong> Include the starting balance you want to project.</li><li><strong>Enter your monthly contribution.</strong> Use the amount you expect to add each month.</li><li><strong>Enter an expected annual return.</strong> This is a calculation assumption, not a guaranteed investment return.</li><li><strong>Click Calculate.</strong> Review projected savings, total contributions and estimated growth.</li><li><strong>Compare scenarios.</strong> Change one input at a time to understand its effect.</li></ol><p>The contribution amount stays constant throughout the calculation. The tool does not automatically increase it with inflation or salary growth.</p></section>

    <section><h3>Understanding the main inputs</h3><h4>Current savings</h4><p>Current savings are the funds you already have available for the projection. This might include a defined contribution pension pot or other retirement savings.</p><p>Avoid entering the same funds twice. A defined benefit pension’s promised annual income is not a savings balance and should not be entered as one.</p><p>If you combine several accounts, remember that a single assumed return may not reflect their different investments, charges and access restrictions.</p><h4>Monthly contribution</h4><p>Your monthly contribution is the amount added to the projected balance after each month’s estimated growth.</p><p>The calculator does not automatically add employer contributions or pension tax relief. If you include these within the monthly amount, use the total expected to reach the account and avoid counting them twice.</p><h4>Expected annual return</h4><p>The expected annual return is the growth assumption used throughout the projection. A higher assumption produces a larger projected balance, but does not make that outcome more likely.</p><p>Actual returns vary over time and can be negative. Compare several assumptions instead of relying on one optimistic result.</p><h4>Time until retirement</h4><p>A longer saving period allows more contributions and more time for compounding. An earlier retirement date gives savings less time to grow and may also mean they need to support you for longer afterwards.</p><p>Your chosen retirement age is a planning input. It does not establish when you can access a pension.</p></section>

    <section><h3>Formula and calculation method</h3><p>The calculator uses monthly compounding and adds contributions at the end of each month.</p><p>The monthly return assumption is:</p><Formula>r = Annual return percentage ÷ 100 ÷ 12</Formula><p>The projection period is the number of whole months between your current age and planned retirement age. For whole-year ages:</p><Formula>n = (Retirement age − Current age) × 12</Formula><p>For a non-zero monthly return, the projected balance follows:</p><Formula>FV = P × (1 + r)<sup>n</sup> + C × ((1 + r)<sup>n</sup> − 1) ÷ r</Formula><p>Where:</p><ul><li><strong>FV</strong> = projected savings at retirement.</li><li><strong>P</strong> = current savings.</li><li><strong>C</strong> = monthly contribution.</li><li><strong>r</strong> = monthly return assumption.</li><li><strong>n</strong> = number of monthly periods.</li></ul><p>At a 0% return:</p><Formula>FV = P + (C × n)</Formula><p>The summary figures are:</p><Formula>Total contributions = Current savings + (Monthly contribution × Number of months)</Formula><Formula>Total growth = Projected savings − Total contributions</Formula><p>The annual percentage is divided by 12 for the monthly calculation. It is not converted from an effective annual return using a twelfth-root calculation.</p></section>

    <section><h3>Example retirement savings calculation</h3><p>Suppose you enter:</p><Table headers={["Input", "Example"]} rows={[["Current age","30"],["Planned retirement age","67"],["Current savings","£20,000"],["Monthly contribution","£300"],["Expected annual return","5%"]]} /><p>The saving period is <strong>37 years</strong>, or <strong>444 months</strong>. The monthly return assumption is approximately <strong>0.4167%</strong>.</p><Table headers={["Result", "Estimated amount"]} rows={[["Starting savings","£20,000.00"],["Additional monthly contributions","£133,200.00"],["Total contributions, including starting savings","£153,200.00"],["Estimated growth","£357,658.87"],["Projected savings at retirement",<strong key="value">£510,858.87</strong>]]} /><p>This example assumes the same return throughout the period and a £300 contribution after every month’s growth.</p><p>The projected amount is a future cash value. It is not adjusted for inflation and does not include separate deductions for fees or tax. The 5% return is illustrative, not a forecast or guarantee.</p></section>

    <section><h3>What does retirement mean?</h3><p>Retirement can mean leaving paid work completely, reducing your working hours or moving gradually into part-time employment.</p><p>Your decision may depend on health, family commitments, job satisfaction and financial readiness. Someone choosing early retirement may need a different savings plan from someone continuing to work for several more years.</p><p>The aim of retirement planning is to understand how your resources could support the life you want after employment income reduces or stops.</p></section>

    <section><h3>Retirement age and pension access</h3><p>Your planned retirement date, private pension access age and State Pension age can be different.</p><p>Most people can currently access private pension savings from age 55, with the normal minimum pension age increasing to 57 from 6 April 2028. Exceptions can apply, including certain protected pension ages and ill-health circumstances.</p><p>State Pension age follows separate rules. Check your own date and the access conditions for each pension scheme. The calculator does not apply these restrictions automatically.</p></section>

    <section><h3>How much should you save for retirement?</h3><p>A projected pension pot is only one part of retirement planning. You also need an estimate of your future spending and the income available to meet it.</p><p>Start with a retirement budget:</p><Table headers={["Spending category","Examples"]} rows={[["Housing","Rent, mortgage repayments, maintenance and service charges"],["Household essentials","Food, energy, water, Council Tax or domestic rates"],["Transport","Public transport, vehicle running costs and insurance"],["Lifestyle","Holidays, hobbies, entertainment and eating out"],["Family commitments","Gifts, financial support and caring responsibilities"],["Health and care","Dental costs, home adaptations and possible care expenses"],["Unexpected costs","Repairs, replacement appliances and emergencies"]]} /><p>Some costs may fall when you stop working, while others may rise. Continuing to rent or repay a mortgage can make a substantial difference.</p><p>Compare spending with expected pension income to identify the amount that savings and investments may need to provide. Keep after-tax spending and before-tax income clearly separated.</p></section>

    <section><h3>Retirement savings rules of thumb</h3><p>The following rules are broad planning references. They are not built into this calculator and do not establish a suitable savings target for everyone.</p><h4>The 10% rule</h4><p>The “10% rule” describes saving around 10% of income for retirement. Some versions suggest 10%–15%.</p><p>For example, 10% of a £40,000 salary is £4,000 a year, or approximately £333 a month.</p><p>Whether this is enough depends on when you start, your existing savings, employer contributions and retirement goals. Check whether any percentage you use includes employer payments and whether it applies to full salary or only pensionable earnings.</p><h4>The 80% rule</h4><p>The “80% rule” uses around 70%–80% of pre-retirement income as an initial retirement income target.</p><p>For someone earning £40,000, this suggests £28,000–£32,000 a year. However, individual spending matters more than a fixed percentage. Housing costs, dependants, travel plans and tax can all change the amount required.</p><h4>The 4% rule</h4><p>The “4% rule” describes withdrawing 4% of an investment portfolio’s starting value in the first year of retirement, then adjusting that cash amount for inflation in later years.</p><p>It does not mean taking 4% of the remaining balance every year. It comes from historical US research and is not a guaranteed safe withdrawal rate for UK retirees.</p><p>As an arithmetic illustration, a £12,000 annual withdrawal at an initial 4% rate corresponds to:</p><Formula>£12,000 ÷ 0.04 = £300,000</Formula><p>This does not prove that £300,000 will provide that income for life. Investment performance, retirement length, fees, tax and inflation affect sustainability. This calculator does not model withdrawals or test the 4% rule.</p></section>

    <section><h3>Inflation and the purchasing power of retirement savings</h3><p>Inflation means money can buy less as prices rise. A large future savings balance may have considerably less purchasing power than the same amount today.</p><p>For example, spending of £24,000 a year today would rise to approximately <strong>£39,327 after 20 years</strong> if inflation averaged an illustrative 2.5% annually:</p><Formula>£24,000 × (1.025)<sup>20</sup> = £39,327</Formula><p>This is an example, not an inflation forecast.</p><p>The calculator displays <strong>nominal values</strong>, meaning future cash amounts without an inflation adjustment. It does not show the equivalent value in today’s money.</p></section>

    <section><h3>Sources of retirement income in the UK</h3><h4>State Pension</h4><p>The State Pension provides government retirement income from State Pension age. Your entitlement depends on your National Insurance record and the rules applying to you.</p><p>Check your personal forecast rather than assuming you will receive the full amount. State Pension income is not included in this calculator’s savings projection.</p><h4>Workplace pensions</h4><p>Workplace pensions can build retirement benefits through employee and employer contributions. Check what your employer pays and whether higher contributions are available when you increase your own payments.</p><p>Two common pension structures are:</p><Table headers={["Pension type","How it works"]} rows={[["Defined contribution","Builds an invested pot whose value depends on contributions, returns and charges"],["Defined benefit","Provides income calculated under scheme rules, commonly using salary and service"]]} /><p>Defined benefit schemes are often described as final salary or career average pensions. Their promised annual income should be considered separately from the savings balance modelled here.</p><h4>Personal pensions and SIPPs</h4><p>A personal pension is arranged independently of an employer. A self-invested personal pension, or <strong>SIPP</strong>, generally offers a wider choice of investments.</p><p>These can form part of retirement planning for self-employed people or those saving alongside a workplace pension. Investment selection, charges and risk still require attention.</p><p>Eligible pension contributions can receive tax relief, subject to applicable rules and limits. The calculator does not assess eligibility, calculate relief or enforce pension contribution allowances.</p><h4>ISAs and personal savings</h4><p>Cash ISAs and Stocks and Shares ISAs can complement pension savings. Income and gains held within an ISA receive UK tax advantages under the applicable rules.</p><p>Accessible savings may help cover emergencies or the period before pension access. Check account restrictions and consider the effect of inflation on cash holdings.</p><h4>Investments and compound growth</h4><p>Retirement investments can include shares, investment funds, index funds, exchange-traded funds, bonds and UK government gilts. Some people also hold property or commodities.</p><p>Compound growth occurs when returns remain invested and can generate further returns. The calculator illustrates this mathematically, but actual investments do not grow at a constant rate.</p><p>Diversification spreads exposure across investments. It can reduce reliance on one holding, although it cannot eliminate the risk of loss.</p></section>

    <section><h3>Taking an income after retirement</h3><p>Building savings and drawing an income from them are different stages. This calculator covers the saving stage only.</p><h4>Pension drawdown</h4><p>Drawdown allows money to remain invested while you take withdrawals. It offers flexibility, but investment losses and excessive withdrawals can reduce how long the fund lasts.</p><h4>Annuities</h4><p>An annuity converts some or all of a pension pot into guaranteed income for life or an agreed period. Options such as increasing payments or income for a surviving partner affect the initial amount payable.</p><h4>Lump sums</h4><p>Pension money may also be accessible through lump-sum withdrawals. Tax treatment depends on how money is taken and the applicable allowances. Large withdrawals can reduce future income resources and affect your tax position.</p></section>

    <section><h3>Other retirement resources</h3><h4>Home equity and property</h4><p>Home equity is the property value remaining after borrowing secured against it is deducted. Downsizing may release money, although moving expenses and replacement housing costs reduce the amount available.</p><p>Equity release has different structures. A <strong>lifetime mortgage</strong> is borrowing secured against your home; <strong>home reversion</strong> involves selling all or part of the property while retaining occupancy rights under the agreement.</p><p>These decisions can affect your estate and future options. Seek regulated advice before proceeding.</p><h4>Rental income and passive income</h4><p>Rent, dividends, royalties and business income can supplement retirement resources. They are not necessarily guaranteed or free from ongoing work.</p><p>Allow for costs, tax and interruptions to income. For property, this includes maintenance and periods without tenants. Keep these income estimates separate from the calculator’s projected savings balance.</p><h4>Part-time work</h4><p>Phased retirement or part-time employment can reduce reliance on savings. However, health, caring responsibilities and job availability may affect how long you can continue working.</p><h4>Inheritance</h4><p>An inheritance may add to retirement resources, but its timing and value are uncertain. Avoid treating an expected inheritance as guaranteed funding.</p></section>

    <section><h3>Life expectancy and investment risk</h3><p>Retirement savings may need to support you for several decades. A plan based only on average life expectancy may be insufficient if you live longer.</p><p>The timing of investment returns also matters once withdrawals begin. Market losses early in retirement can be particularly damaging when money is being withdrawn at the same time. This is called <strong>sequence-of-returns risk</strong>.</p><p>The calculator does not model this risk, market volatility or the period after retirement. A smooth growth projection should not be interpreted as proof that a fund will provide a sustainable lifetime income.</p></section>

    <section><h3>Getting useful results</h3><p>Compare scenarios such as:</p><ul><li>Increasing or reducing monthly contributions.</li><li>Retiring earlier or later.</li><li>Using a lower expected annual return.</li><li>Starting with a different savings balance.</li></ul><p>Keep the assumptions realistic and review them regularly. A projected shortfall may prompt you to reconsider contributions, timing or spending, but the calculator cannot determine the best action for your circumstances.</p></section>

    <section><h3>Assumptions and limitations</h3><p>The projection assumes a constant return, monthly compounding and an unchanged contribution added at the end of each month.</p><p>It does not automatically model:</p><ul><li>Inflation or purchasing power.</li><li>Market volatility or investment losses occurring in a particular sequence.</li><li>Fees or tax deductions.</li><li>Pension access rules or contribution limits.</li><li>Employer matching or pension tax relief.</li><li>State Pension or defined benefit pension income.</li><li>Withdrawals, annuities or retirement income sustainability.</li><li>Changes in earnings, contributions or personal circumstances.</li></ul><p>If you include employer contributions within your monthly input, or adjust your return assumption to allow for fees, those remain your own assumptions. The calculator does not calculate or verify them separately.</p></section>

    <section><h3>Important information</h3><p>This retirement calculator provides a simplified savings projection based on your inputs. It is not financial advice, does not guarantee future returns and should not be the only basis for retirement decisions.</p><p>Check your pension statements, State Pension forecast and scheme rules. MoneyHelper offers pensions guidance, and eligible people with UK defined contribution pensions can use Pension Wise to understand their options for accessing pension savings. Consider regulated financial advice for decisions about investments and retirement income.</p></section>
  </article>;
}
